environment:
  nuget_version: '2.5.2'
  nuget_prerelease: false
  assembly_version: '2.5.2'

version: '$(nuget_version)+{build}'

deploy:
  - provider: GitHub
    description: |
      * Fixed slow test discovvery for large solutions (#74 - @bjuris)

    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)

    release: v$(nuget_version)
    auth_token:
      secure: VrF5TrpBRN0ims9nJC1LG32O6ga5hsRuGNSufEbatAiIWZ1z68iiCYKZtqnAaT9y

  - provider: NuGet
    api_key:
      secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
      appveyor_repo_tag: true


clone_depth: 5

pull_requests:
  do_not_increment_build_number: true

configuration: Release
platform: Any CPU

image: Visual Studio 2017

build_script:
- cmd: >-
    dotnet restore

    dotnet build

    dotnet test Source\Machine.VSTestAdapter.Specs\Machine.VSTestAdapter.Specs.csproj

    dotnet pack Source\Machine.VSTestAdapter\Machine.VSTestAdapter.csproj -c Release /p:Version=%NUGET_VERSION%

test: off

artifacts:
- path: Source\**\*.nupkg

