environment:
  nuget_version: '2.6.0-beta2'
  assembly_version: '2.6.0'
  nuget_prerelease: true

version: '$(nuget_version)+{build}'

pull_requests:
  do_not_increment_build_number: true

configuration: Release
image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(nuget_version)'
  assembly_version: '$(assembly_version)'

before_build: dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal  

test_script: dotnet test -c %CONFIGURATION% Source\Machine.VSTestAdapter.Specs

deploy:
  - provider: GitHub
    description: |
      * Fix to support for VS 2017 15.5.x

    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)

    release: v$(nuget_version)
    auth_token:
      secure: VrF5TrpBRN0ims9nJC1LG32O6ga5hsRuGNSufEbatAiIWZ1z68iiCYKZtqnAaT9y

  - provider: NuGet
    api_key:
      secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
      appveyor_repo_tag: true