environment:
  nuget_version: '2.2.1'
  nuget_prerelease: false
 # vsix_version: '2.1.0'
  assembly_version: '2.1.0'

version: '$(nuget_version)+{build}'

deploy:
  - provider: GitHub
    description: |
      * Support for .NET Core Test Projects (Visual Studio IDE, dotnet test and vstest.console). NOTE: Line numbers for tests are not working currently for .NET Core targets.
   

    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)

    release: v$(nuget_version)
    auth_token:
      secure: VrF5TrpBRN0ims9nJC1LG32O6ga5hsRuGNSufEbatAiIWZ1z68iiCYKZtqnAaT9y

  - provider: NuGet
    api_key:
      secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
      appveyor_repo_tag: true


clone_depth: 5

pull_requests:
  do_not_increment_build_number: true

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: Source\**\AssemblyInfo.*
  assembly_version: '$(assembly_version).{build}'
  assembly_file_version: '$(assembly_version).{build}'
  assembly_informational_version: '$(nuget_version)'

#before_build:
#- cmd: >-
#    powershell -f patch-vsix-version.ps1 -version "%VSIX_VERSION%.%APPVEYOR_BUILD_NUMBER%" -manifestFile "Source\Machine.VSTestAdapter.VSIX\source.extension.vsixmanifest"

image: Visual Studio 2017

build_script:
- cmd: >-
    dotnet restore

    dotnet build

    dotnet test Source\Machine.VSTestAdapter.Specs\Machine.VSTestAdapter.Specs.csproj

    dotnet pack Source\Machine.VSTestAdapter\Machine.VSTestAdapter.csproj -c Release /p:Version=%NUGET_VERSION%

test: off

artifacts:
- path: Source\**\*.nupkg

